### ISSUE TITLE
[Opinion] Increase min Node version

### ISSUE THREAD

**Issue by rafakato** [ThomWright/postgres-migrations#3]
What do you think of defining the min node version to the latest [LTS](https://github.com/nodejs/Release#release-schedule) (Carbon)?

Some things I considered:
 - It allows us to use `async/await` that would make the code better to read;
 - npm@5

If you agree I can do the refactoring to `async/await`

**Comment by ThomWright** [comment]
I think you already made that change in #2 here: https://github.com/ThomWright/postgres-migrations/pull/2/files/a614a1aa1a7308e15c4ad5cb38d3dcd2f9d8159a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R26 ;)

I was going to comment since it didn't seem necessary, but I'm happy to bump this up to Node 8.9.

Using `async/await` would probably make the code a bit nicer, so go ahead.
